name: Guias y cursos
description: Sugiera una idea para el proyecto
title: "[游닄]: Semestre []"
labels: ["content"]
body:
  - type: markdown
    attributes:
      value: |
        Recordar que para que esta gu칤a sea marcada como completada tiene que tener la siguiente estructura:
        - [ ] Temas (detallar qu칠 temas se desarrollan en el curso)
        - [ ] Libros (junto a comentarios de los motivos de la recomendaci칩n)
          - Te칩ricos
          - Pr치cticos
        - [ ] Videos (por ejemplo, puede incluir canales de Youtube)
        - [ ] S칤labo
  - type: input
    id: curso
    attributes:
      label: Curso
      description: Escriba el nombre del curso
      placeholder: |
        Ejemplo: "츼lgebra Lineal"
    validations:
      required: true
  - type: input
    id: codigo
    attributes:
      label: C칩digo
      description: Escriba el c칩digo del curso
      placeholder: |
        Ejemplo: "CFO304"
    validations:
      required: true
  - type: checkboxes
    id: autor
    attributes:
      label: Autor
      description: |
        쮼s usted miembro de CAE - F칤sica? No es necesario marcar que s칤 para crear esta solicitud.
      options:
        - label: Confirmo
        - label: No soy miembro