package main

import (
    "bufio"
    "context"
    "fmt"
    "io/ioutil"
    "os"
    "path/filepath"
    "strings"

    "github.com/chromedp/chromedp"
)

func main() {
    // For the action to work, we need to set the root as GITHUB_WORKSPACE
    root := os.Getenv("GITHUB_WORKSPACE")

    // If not set to 1920x1080, the screenshot will look ugly
    width, height := 1920, 1080

    // Reading from a file generated by markdown scanner
    file, err := os.Open(filepath.Join(root, "assets", "go", "lists.txt"))
    if err != nil {
        fmt.Println(err)
        return
    }
    defer file.Close()

    scanner := bufio.NewScanner(file)
    var websites []string
    for scanner.Scan() {
        website := strings.TrimSpace(scanner.Text())
        if website != "" {
            websites = append(websites, website)
        }
    }

    opts := append(chromedp.DefaultExecAllocatorOptions[:],
        chromedp.Flag("headless", true),
        chromedp.Flag("disable-gpu", true),
        chromedp.Flag("no-sandbox", true),
        chromedp.Flag("disable-setuid-sandbox", true),
    )

    allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)
    ctx, cancel := chromedp.NewContext(allocCtx)
    defer cancel()

    for _, website := range websites {
        err := chromedp.Run(ctx, chromedp.Navigate(website))
        if err != nil {
            fmt.Println(err)
            continue
        }

        err = chromedp.Run(ctx, chromedp.EmulateViewport(int64(width), int64(height)))
        if err != nil {
            fmt.Println(err)
            continue
        }

        var buf []byte
        err = chromedp.Run(ctx, chromedp.CaptureScreenshot(&buf))
        if err != nil {
            fmt.Println(err)
            continue
        }

        websiteDir := strings.Replace(website, "https://", "", 1)
        websiteDir = strings.Replace(websiteDir, "http://", "", 1)
        websiteDir = strings.Replace(websiteDir, "www.", "", 1)
        websiteDir = strings.TrimSuffix(websiteDir, "/")

        resultDir := filepath.Join(root, "content", "experimental")
        if _, err := os.Stat(resultDir); os.IsNotExist(err) {
            os.MkdirAll(resultDir, os.ModePerm)
        }

        websiteDir = filepath.Join(resultDir, websiteDir)
        if _, err := os.Stat(websiteDir); os.IsNotExist(err) {
            os.MkdirAll(websiteDir, os.ModePerm)
        }

        filename := filepath.Join(websiteDir, fmt.Sprintf("%s.png", websiteDir))
        err = ioutil.WriteFile(filename, buf, os.ModePerm)
        if err != nil {
            fmt.Println(err)
            continue
        }
        fmt.Printf("Screenshot of %s saved to %s\n", website, filename)
    }
}
