name: 💡 Experiencia del usuario

on:
    workflow_dispatch:
    push:
        branches: [master]
        paths:
            - '/layouts/'
            - '/assets/'
            - '/functions/'

jobs:
    lighthouse:
        name: Experiencia del usuario
        runs-on: ubuntu-latest

        steps:
            - name: Inicializar Github Action
              uses: actions/checkout@v6

            - name: Auditar usando Lighthouse
              uses: treosh/lighthouse-ci-action@v12
              with:
                  urls: |
                      https://caefisica.com/
                      https://caefisica.com/blog/
                  budgetPath: ./.github/budget.json
                  uploadArtifacts: true
                  temporaryPublicStorage: true
