name: 👷 CI/CD (Node.JS)

on:
    workflow_dispatch:
    pull_request:
        paths:
            - '/layouts/'
            - '/assets/'
            - '/functions/'
    push:
        branches: [master]
        paths:
            - '/layouts/'
            - '/assets/'
            - '/functions/'

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [22.x, 24.x]

        steps:
            - name: Install libvips (Ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y libvips git-lfs

            - name: Inicializar Github Action
              uses: actions/checkout@v6
              with:
                  lfs: true

            - name: Instalar pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Instalar Node.js ${{ matrix.node }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node }}
                  cache: pnpm

            - name: Instalar dependencias
              run: pnpm install --frozen-lockfile

            - name: Análisis lint
              run: pnpm test

            - name: Construir sitio
              run: pnpm run build
